table1NumPar:
  title: "Table - Number of participants"
  function: table1NumPar(incidence_attrition, prevalence_attrition)
  type:
    - incidence_attrition
    - prevalence_attrition
  options: NULL
table1IncAtt:
  title: "Table - Incidence Attrition"
  function: table1Att(incidence_attrition, attritionDataType)
  type:
    - incidence_attrition
  options: NULL
table1PrevAtt:
  title: "Table - Prevalence Attrition"
  function: table1Att(prevalence_attrition, attritionDataType)
  type:
    - prevalence_attrition
  options: NULL
table1Inc:
  title: "Table - Number of participants by sex and age group"
  function: table1Inc(incidence_estimates)
  type:
    - incidence_estimates
  options: NULL
plotIncidenceYear:
  title: "Plot - Incidence rate per year"
  function: plotIncidence(incidence_estimates, colour, facet, ribbon, options)
  type:
    - incidence_estimates
  options: Facet by outcome, Facet by database, Ribbon, Options
plotIncidenceSex:
  title: "Plot - Incidence rate per year by sex"
  function: plotIncidence(incidence_estimates, colour, facet, ribbon, options)
  type:
    - incidence_estimates
  options: Facet by outcome, Facet by database, Ribbon, Options
plotIncidenceAge:
  title: "Plot - Incidence rate per year by age"
  function: plotIncidence(incidence_estimates, colour, facet, ribbon, options)
  type:
    - incidence_estimates
  options: Facet by outcome, Facet by database, Ribbon, Options
plotPrevalenceYear:
  title: "Plot - Prevalence per year"
  function: plotPrevalence(prevalence_estimates, colour, facet, ribbon, options)
  type:
    - prevalence_estimates
  options: Facet by outcome, Facet by database, Ribbon, Options
plotPrevalenceSex:
  title: "Plot - Prevalence per year by sex"
  function: plotPrevalence(prevalence_estimates, colour, facet, ribbon, options)
  type:
    - prevalence_estimates
  options: Facet by outcome, Facet by database, Ribbon, Options
plotPrevalenceAge:
  title: "Plot - Prevalence per year by age"
  function: plotPrevalence(prevalence_estimates, colour, facet, ribbon, options)
  type:
    - prevalence_estimates
  options: Facet by outcome, Facet by database, Ribbon, Options
treatmentPathways:
  title: "Treatment Pathways Interactive Plots"
  type:
    - treatmentPathways
createSunburstPlot:
  title: "Sunburst Plot - TreatmentPatterns"
  function: createSunburstPlot(treatmentPathways, groupCombinations)
  options: TRUE, FALSE
  type:
    - plot
createSankeyDiagram:
  title: "Sankey Diagram - TreatmentPatterns"
  function: createSankeyDiagram(treatmentPathways, groupCombinations)
  options: TRUE, FALSE
  type:
    - diagram
summaryCharacteristics:
  title: "Summarised Characteristics"
  function: gtCharacteristics(summarisedCharacteristics)
  type:
    - summarised_characteristics
summarised_large_scale_characteristics:
  title: "Summarised Large Scale Characteristics"
  function: gtCharacteristics(summarisedCharacteristics)
  type:
    - summarised_large_scale_characteristics
Survival table:
  title: "Survival table"
  function: cohortSurvivalTable(survivalEstimate)
  type:
    - Survival estimate
Survival plot:
  title: "Survival plot"
  function: CohortSurvival::plotSurvival(survivalEstimate, facet, colour)
  type:
    - Survival estimate
  options: Facet by database, colour by strata_name
Cumulative incidence table:
  title: "Cumulative incidence table"
  function: cohortSurvivalTable(cumulativeSurvivalEstimate)
  type:
    - Survival cumulative incidence
Cumulative incidence plot:
  title: "Cumulative incidence plot"
  function: CohortSurvival::plotCumulativeIncidence(cumulativeSurvivalEstimate, facet, colour)
  type:
    - Survival cumulative incidence
  options: Facet by database, colour by strata_name
